library(MASS)
library(gam)
library(compiler)
library(shape)
library(sp)
library(maptools)
library(signal)
library(fields)
library(KernSmooth)
library(glogis)
library(car)
library(biseVec)

data <- read.csv("E:\\NASA_NERP\\HotspotFFDI\\data\\results\\Trial2\\complete_frame_N.csv")
